- libstorage/include/storage/dev.h
`_storage_devCtx_t` defines data used by specific flash memory driver.
PD-216
> storage/dev.h: use device driver context instead of id

- libgraph/cirrus.c
- libgraph/vga.c
Fix endless loop when set or get the (full) 256 color palette.
Example case when error occurred:
```C
/* for (8-bit palette) indexed 256 color mode */
unsigned char palette[3 * 256];
...
graph_colorset(graph, palette, 0, 255);
```
JIRA: RTOS-186
> libvga: Fix infinite loop in `graph_colorset/get()`

- libmtd/mtd.c
- libstorage/include/storage/dev.h
- the `oobSize` and the `oobAvail` fields are added into storage_mtd_t - there are needed for a NAND driver
- instead of adding a partition offset in a driver implementation, it has been moved to a higher layer
- small changes in `mtd_oob*` functions
DTR-102
> libmtd & libstorage: update strogae_mtd_t and mtd functions

- libstorage/storage.c
The requests are queued up by adding them to the queue tail. In order to process requests in FIFO order we should remove them from the queue head.
[JIRA: RTOS-190](https://jira.phoenix-rtos.com/browse/RTOS-190)
> libstorage: fix requests processing order (FIFO instead of LIFO)

- libuuid/uuid.c
- libuuid: decrease the execution time of uuid_useRand()
Generating large amount of uuids (test-libuuid) on targets, where /dev/random is not present took more time.
The tv_nsec resolution is commonly lower than or equal to 1ms, so the change does not decrease usability.
DONE: RTOS-235
> libuuid: decrease the execution time of uuid_useRand()

- libuuid/uuid.c
- libuuid: avoid setting the same seed
The problem with generating same uuids might have occurred, when not using `/dev/random`. The change solves it.
JIRA: RTOS-239
> libuuid: avoid setting the same seed

- libmtd/include/mtd/mtd.h
- libmtd/mtd.c
Based on linux mtd API argument `phys` is a type of `resource_size_t;`
`resource_size_t` is a typedef to `phys_addr_t`. For this reason, type of `phys` argument in `mtd_point` is changed to `addr_t`. 
Wrong argument type causes warning on `ia32-generic-pc` target.
RTOS-244
> libmtd: change type of argument in mtd_point function

- libcache/cache.c
- libcache/cache.h
The `size_t size` argument of `cache_init` function has been removed from the function prototype and `size_t linesCnt` has been added instead. 
This change shifts the responsibility of proper cache configuration from the user onto the library.
Now, the `cache_init` header is more intuitive as it resembles the typical formulation of function prototypes, e.g. from standard library:
-  _elementSize_ and _numOfElements_ (new API) vs.
-  _elementSize_ and _sizeOfAllElementsCombined_ (old API),
> Change cache_init function header in libcache API

- libstorage/include/storage/fs.h
- libstorage/include/storage/storage.h
- libstorage/storage.c
Added mount point oid stored for every mounted filesystem.
[JIRA: RTOS-293](https://jira.phoenix-rtos.com/browse/RTOS-293)
> libstorage: add mountpoint info to mounted filesystems

- libstorage/fs.c
JIRA: RTOS-346
Add mtDevCtl support.
Add errors support to mtOpen and mtClose.
Meterfs starts to use libstorage. It needs proper mtDevCtl support in order to work.
> Add mtDevCtl support to storage_fsHandler

- libvirtio/virtio.h
JIRA: RTOS-396
fixes `htole##n` concatenation for big endian targets
JIRA: RTOS-396
> libvirtio: fix htole##n macro concat

- libptable/ptable.c
It allows building host-utils separately
JIRA: CI-254
> libptable: don't include board_config for host

- libptable/ptable.c
Change introduced so that `libptable` can also be built on a non-linux host, e.g. BSD.
btw `phoenix` builtin define is in gcc config `gcc-9.3.0/gcc/config/phoenix.h`
References:
phoenix-rtos-corelibs/pull/ https://github.com/phoenix-rtos/phoenix-rtos-corelibs/pull/36
JIRA: RTOS-423
> libptable: remove linux host dependency

- libptable/ptable.c
- libptable/ptable.h
Use new version field to enable/disable CRC check
DONE: RTOS-422
My proposition for enabling/disabling CRC checks in runtime - add additional version field to disable checks only on legacy ptables (that did not have this version field).
> ptable: Remove board_config.h dependency

- libstorage/storage.c
Initializing with NULL is technically not required, but it determining is non-trivial.
> storage: remove mabye-uninitialized GCC warning

- libptable/ptable.c
- lbptable: redefine endian functions on MacOS
le32toh() is not available on MacOS, that's why we use OSSwapLittleToHostInt32() from libkern/OSByteOrder.h on this platform.
JIRA: RTOS-443
> libptable: redefine endian functions on MacOS

- libstorage/storage.c
JIRA: RTOS-468
Recent changes in libstorage shed light onto a fact that `storage_reqthr` locks the same mutex at the begging of the for loop as it unlocks at the end.
> libstorage: remove redundant lock unlock

- libgraph/virtio-gpu.c
The reason for this is a recent change to phoenix-rtos-build which provides `__TARGET` and `__CPU` globally.
`TARGET_RISCV64` becomes `__TARGET_RISCV64` and `__CPU_GENERIC`.
JIRA: RTOS-519
> libgraph: adjust TARGET define on riscv64

- libstorage/fs.c
- libstorage/include/storage/fs.h
- return devctl error only via output argument,
- return -ENOTTY when no devctl handler is provided to return valid errno from ioctl()
JIRA: RTOS-525
> libstorage: Fix ioctl() handling on fs

- libptable/Makefile
CI to pass: https://github.com/phoenix-rtos/phoenix-rtos-project/pull/815
> make: remove addition of PROJECT_PATH include path

- libgraph/cirrus.c
- libgraph/virtio-gpu.c
- libvga/vgahw-pc.c
- libvirtio/virtio.c
- libvirtio/virtiopci.c
- libvirtio/virtqueue.c
JIRA: RTOS-665
Adjust mmap to POSIX standard.
https://github.com/phoenix-rtos/libphoenix/pull/306
> Adjust mmap calls to new interface

- Makefile
- libmbr/Makefile
- libmbr/mbr.c
- libmbr/mbr.h
JIRA: RTOS-734
Add simple library for MBR partition handling.
Use in disk drivers
> add libmbr

- Makefile
- libmodbus/Makefile
- libmodbus/buffer.c
- libmodbus/buffer.h
- libmodbus/include/modbus.h
- libmodbus/modbus.c
Modbus RTU master (client) library. 
Not all functionalities are implemented yet, but things that were needed for now should be there.
This was developed primarily for the use in Cognit Project.
See: https://github.com/SovereignEdgeEU-COGNIT/use-case-3-phoenix-demo
> libmodbus: initial version of the library
